language: python

env:
  global:
    secure: cB+yVOL/QSh0nWRk0/ydxz/ConXliBMB4bRZCayZEYW9qtGtaaOFdt7VIaBxRlvrDB8/bXM5Wvo/caGO4KneQLJ3aZkjK+k7xZRypRoILXGtLrMIfK6zcznXZFPK+l+N5Mtkq0djuHjeNk7h6ptQeMMV3zeb0ZZOUACvr/Ss5cIbWpl3t03LibtC0kyudLwbCq/3KKii/S2pTQlucTgDy9qQtESEclN20AOUK9FH3ffM+tUAjAzQBWyYzMB+LKwPHMwTkHIaAjtjsMXtX95XOqL5s+XgB+aufG2JbpjTEo/ksQeTIOysHYpUILz9eYDL0vWxO7DVMUn1cWnPYijTvCQnC5NgY6yJ3pJDARZ843UHZE9GE9K71gXEMPkGBeEzqCw5zWocuSgDQ/kiSl1oHqH+SOnsgxgwmAQH5kVdO3r3KmnZTLNCKD9SNf90isANse9cCoWD0q6n9GahiKGrtVUvsUzzmVJ+z/+ZO4Zu48ie6X8LPtFpK+6LLQI8vAsn9ykqJGY2A7pF1wLkCfdzI+9nSPDbl7woaX6pvVlVrqxUefWrg/cyFzF/sbWR1X+aqbxYhvn6v8FNu1pwwyCLOc/N0szoODJCLQLHQb3CEtYmEytBJI9F46pUNJGexJQnSj1GOYgE9tmNkPsmeHnoINvCRFU2NZLfIduyvBS2mJQ=

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
 - tox
 - .travis/update-hashinfo

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --pro --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mgerstel
  password:
    secure: lPz5OabrKGY/TqhdGRlObnFfnjZQdySV98V83vRQGBoIZKbyhHsWYxHM0dVwKe7LbiyWhYwE40LW0nureUridJ8LB5uqvJuS7drWsQV4XJpoqPGDgxK2/P0UWCHzSz4coTSBNT8/dl8Xg8rEjs7GBZnQQrAv8BV0PzkVhVQZz+3dGQfSjveeX2S0xR10u2JwHQ+jSHBmIxN7PCNBjcnWLKZaB4qL2ct4zhJK8LgIrOBcoEN+XmYxox/Ip1NfKhAbrVQIMXJ5McsuImn5DeJgr7ZHvyb0KcpeUB86SzFUCFW4RPOE6s4s2CPILZabZ+HvHU3JUI64Dx+kQLjNZoUWDWdXPwXW0WHV8HbSyj6lfRSsvjCNz3hZOlrFypRzlw4beZJaoDHQqT7KJaVwVU0IlbyilDxq5GmK7qQPpbKPBz95KMB6lMFKoCgBwnknsdjen0jVYymvHI1K9YPsOsvbb3HaK29gq6aP5cb6eJS37/M6Eo0E0rHnglG/aUBK1FN9m/WNBeWTTxbvujsYxodjWcoF0S24rC2L/0cKCUNji3Q1VFevg1rouprlCz28mFAn0bLG2FLsqakaQOWcj/DhPYBVXIeruce5RggKXGWr1dow20kAYdpZ/ib0tTC+5nR6JyBZF7ZlLJRty+YuLnPzG9pVdiO/Vpo01o8Qqk+138M=
  on:
    tags: true
    repo: dials/data
    python: 3.7
